stages:
  - test

tests::unit:
  stage: test
  image: $IMAGE
  parallel:
    matrix:
      - IMAGE: ['python:3.6-slim', 'python:3.7-slim', 'python:3.8-slim', 'python:3.9-slim']
  script:
    - pip install pytest pytest-cov
    - pip install .
    - pytest --junitxml=report.xml --cov=foris_schema --cov-report=term 
  artifacts:
    reports:
      junit: report.xml
      cobertura: coverage.xml
  coverage: /^TOTAL.*\s+([^\s]+)%$/

tests::cli:
  stage: test
  image: $IMAGE
  parallel:
    matrix:
      - IMAGE: ['python:3.6-slim', 'python:3.7-slim', 'python:3.8-slim', 'python:3.9-slim']
  script:
    - pip install pytest pytest-cov
    - pip install .
    - pytest tests/test_cli.py
