stages:
  - test

test_python3:
  stage: test
  image: $IMAGE
  parallel:
    matrix:
      - IMAGE: ['python:3.6-slim', 'python:3.7-slim', 'python:3.8-slim', 'python:3.9-slim']
  script:
    - pip install pytest
    - pip install .
    - pytest

test_cli:
  stage: test
  image: $IMAGE
  parallel:
    matrix:
      - IMAGE: ['python:3.6-slim', 'python:3.7-slim', 'python:3.8-slim', 'python:3.9-slim']
  script:
    - pip install pytest
    - pip install .
    - pytest tests/test_cli.py 
